stages:
  - debug

publish:s3:
  stage: debug
  image: debian:buster
  script:
    - echo $CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^pr_25$/'
    - if: '$CI_COMMIT_REF_NAME !~ /^pr_25$/ && $CI_COMMIT_REF_NAME'
      when: manual
