GRUB_VERSION="2.06"

GRUB_MODULES="boot linux ext2 fat serial part_msdos part_gpt normal \
              efi_gop iso9660 configfile search loadenv test \
              cat echo gcry_sha256 halt hashsum sleep reboot regexp \
              loadenv test cryptodisk luks luks2 crypto \
	      gcry_arcfour gcry_blowfish gcry_camellia gcry_cast5 gcry_crc \
	      gcry_des gcry_dsa gcry_idea gcry_md4 gcry_md5 gcry_rfc2268 \
	      gcry_rijndael gcry_rmd160 gcry_rsa gcry_seed gcry_serpent gcry_sha1 \
	      gcry_sha256 gcry_sha512 gcry_tiger gcry_twofish gcry_whirlpool"
